id: P000312
initial_creation_type: ocr
created_at: 12/03/2020
last_modified_at: 2021-12-16 15:33:26.245936
source_metadata:
  id: bdr:W23794
  title: བཤེས་པའི་འཕྲིན་ཡིག་གི་ཊཱི་ཀ།
  author: ''
  volumes:
    9d0e5ca689bf4df2a6db5a9773896d90:
      image_group_id: I2772
      title: ''
      volume_number: 1
      total_pages: 266
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
