id: I1195E11F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-12T14:57:36+00:00'
last_modified: '2022-06-10T04:00:30.408473+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23794
  title: བཤེས་པའི་འཕྲིན་ཡིག་གི་ཊཱི་ཀ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    73AC:
      image_group_id: I2772
      title: ''
      total_pages: 266
      order: 1
      base_file: 73AC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
